//! 固定账单作为账户页的周期支出，而非独立“自动化”概念。
import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { BellRing, Pencil, Plus, Power, Trash2 } from "lucide-react";
import { createBill, deleteBill, getBills, updateBill, type BillInput } from "../../api";
import { EmptyState } from "../../components/EmptyState";
import { ModalShell } from "../../components/ModalShell";
import { formatMoney } from "../../lib";
import type { Account, Bill, Category } from "../../types";

const blank = (): BillInput => ({ name: "", account_id: 0, category_id: 0, amount: "", due_day: 1, active: true, note: "" });
export function BillSection({ accounts, categories }: { accounts: Account[]; categories: Category[] }) {
  const [bills, setBills] = useState<Bill[]>([]); const [editing, setEditing] = useState<Bill | null>(null); const [creating, setCreating] = useState(false);
  const load = useCallback(async () => { try { setBills(await getBills()); } catch { /* 静默：账户页其他内容保持可用 */ } }, []);
  useEffect(() => { void load(); }, [load]);
  const accountsById = useMemo(() => new Map(accounts.map((item) => [item.id, item])), [accounts]); const categoriesById = useMemo(() => new Map(categories.map((item) => [item.id, item])), [categories]);
  const remove = async (id: number) => { if (!window.confirm("确认删除这项固定账单？")) return; await deleteBill(id); await load(); };
  const toggle = async (item: Bill) => { await updateBill(item.id, { name: item.name, account_id: item.account_id, category_id: item.category_id, amount: item.amount, due_day: item.due_day, active: !item.active, note: item.note }); await load(); };
  return <section className="section-block account-group"><div className="section-heading compact-heading"><div><span>BILLS</span><h2>固定账单</h2></div><button className="text-button" onClick={() => setCreating(true)}><Plus size={16} /> 添加账单</button></div><div className="account-grid">{bills.map((item) => { const account = accountsById.get(item.account_id); return <article className="account-detail-card bill-card" key={item.id}><span className="large-account-icon tone-1"><BellRing size={23} /></span><div className="account-detail-copy"><h3>{item.name}{!item.active && <em>已停用</em>}</h3><span>每月 {item.due_day} 日 · {categoriesById.get(item.category_id)?.name ?? "未分类"} · {account?.name ?? "未知账户"}</span></div><strong>{formatMoney(item.amount, account?.currency ?? "CNY")}</strong><div className="account-card-actions"><button className="row-action" onClick={() => setEditing(item)} aria-label="编辑账单"><Pencil size={16} /></button><button className="row-action" onClick={() => void toggle(item)} aria-label={item.active ? "停用账单" : "启用账单"}><Power size={16} /></button><button className="row-action danger" onClick={() => void remove(item.id)} aria-label="删除账单"><Trash2 size={16} /></button></div></article>; })}{bills.length === 0 && <EmptyState title="没有固定账单" detail="水电、订阅、房租等可在到期前显示提醒。" />}</div>{(creating || editing) && <BillModal bill={editing} accounts={accounts} categories={categories} onClose={() => { setCreating(false); setEditing(null); }} onSaved={() => void load()} />}</section>;
}
function BillModal({ bill, accounts, categories, onClose, onSaved }: { bill: Bill | null; accounts: Account[]; categories: Category[]; onClose: () => void; onSaved: () => void }) { const [draft, setDraft] = useState<BillInput>(() => bill ? { name: bill.name, account_id: bill.account_id, category_id: bill.category_id, amount: bill.amount, due_day: bill.due_day, active: bill.active, note: bill.note } : blank()); const [busy, setBusy] = useState(false); const save = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { bill ? await updateBill(bill.id, draft) : await createBill(draft); onSaved(); onClose(); } finally { setBusy(false); } }; return <ModalShell eyebrow="BILL" title={bill ? "编辑固定账单" : "添加固定账单"} onClose={onClose}><form className="entry-form" onSubmit={(event) => void save(event)}><div className="form-grid"><label><span>名称</span><input required value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })} /></label><label><span>每月到期日</span><input required type="number" min="1" max="31" value={draft.due_day} onChange={(e) => setDraft({ ...draft, due_day: Number(e.target.value) })} /></label><label><span>付款账户</span><select required value={draft.account_id || ""} onChange={(e) => setDraft({ ...draft, account_id: Number(e.target.value) })}><option value="" disabled>请选择</option>{accounts.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>支出分类</span><select required value={draft.category_id || ""} onChange={(e) => setDraft({ ...draft, category_id: Number(e.target.value) })}><option value="" disabled>请选择</option>{categories.filter((item) => item.kind === "expense").map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>预计金额</span><input required type="number" min="0.01" step="0.01" value={draft.amount} onChange={(e) => setDraft({ ...draft, amount: e.target.value })} /></label><label><span>备注</span><input value={draft.note} onChange={(e) => setDraft({ ...draft, note: e.target.value })} /></label></div><div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>取消</button><button className="primary-button" disabled={busy}>{busy ? "保存中" : "保存"}</button></div></form></ModalShell>; }
